spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/wallet
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none